[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

# Dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@fhevm/solidity/=lib/fhevm-solidity/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
fhevm_testnet = "https://testnet.fhevm.zama.ai"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
fhevm_testnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# FHEVM specific settings
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false
